[package]
name = "skp"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.22"
serde = { version = "1.0", features = ["derive"] }
xdg = "3.0.0"
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
clap_complete = "4.5.50"
handlebars = "6.3.2"
serde_json = "1.0.140"
